sudo: required

language: c

services:
  - docker

before_install:
  - cd /travis && docker build -t systemd-container .

script:
  - docker exec -t systemd-container bash -c "cd /travis && swift test;"
