sudo: required

language: c

services:
  - docker

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:xenial tail -f /dev/null

install:
  - docker exec --privileged -t ubuntu-test bash -c "cat /etc/os-release;"
  - docker exec --privileged -t ubuntu-test bash -c "apt-get update;"
  - docker exec --privileged -t ubuntu-test bash -c "apt-get -y install clang-3.8 lldb-3.8 libcurl3 curl libicu-dev libxml2 libpython2.7-dev libsystemd-dev;"
  - docker exec --privileged -t ubuntu-test bash -c "ln -s /usr/bin/clang-3.8 /usr/bin/clang && sudo ln -s /usr/bin/clang++-3.8 /usr/bin/clang++;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && curl -O https://swift.org/builds/swift-4.1-release/ubuntu1604/swift-4.1-RELEASE/swift-4.1-RELEASE-ubuntu16.04.tar.gz;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && tar xzvf swift-4.1-RELEASE-ubuntu16.04.tar.gz;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && echo 'export PATH=/travis/swift-4.1-RELEASE-ubuntu16.04/usr/bin:$PATH' >> ~/.profile;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && echo 'export C_INCLUDE_PATH=/travis/swift-4.1-RELEASE-ubuntu16.04/usr/lib/swift/clang/include/' >> ~/.profile;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && echo 'export CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH' >> ~/.profile;"

script:
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && source ~/.profile && which clang;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && which clang;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && source ~/.profile && swift --version;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && source ~/.profile && swift build;"
  - docker exec --privileged -t ubuntu-test bash -c "cd /travis && source ~/.profile && swift test;"
