language: c

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      script:
        - swift test
    - os: linux
      sudo: required
      services:
        - docker
      before_install:
        - docker build -t systemd-test .
        - docker run --rm --privileged -v /:/host systemd-test setup
        - docker run -d --name systemd-test --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t systemd-test
      script:
        - docker exec -t systemd-test bash -c "swift test;"
