sudo: required

language: c

services:
  - docker

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:xenial tail -f /dev/null

install:
  - docker exec -t ubuntu-test bash -c "apt-get update;
      apt-get -y install clang-3.8 lldb-3.8 libicu-dev libpython2.7-dev wget libsystemd-dev;
      cd /travis;
      wget https://swift.org/builds/swift-4.1-release/ubuntu1404/swift-4.1-RELEASE/swift-4.1-RELEASE-ubuntu14.04.tar.gz;
      tar xzvf swift-4.1-RELEASE-ubuntu14.04.tar.gz;"

script:
  - docker exec -t ubuntu-test bash -c "cd /travis &&
      export PATH=/travis/swift-4.1-RELEASE-ubuntu14.04/usr/bin:$PATH &&
      swift test;"
