comment:
  layout: header, changes, diff, tree
coverage:
  ignore:
    - Tests/.*
    - Pods/.*
    - vendor/.*
    - Carthage/.*
    - build/.*
    - .build/.*
    - .vagrant/.*

  status:
    patch: false
